# Generated by Django 2.2 on 2019-07-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('poltrona', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('chassi', models.CharField(max_length=50)),
                ('qtd_pessoas', models.IntegerField()),
                ('km_rodados', models.IntegerField()),
                ('leito', models.BooleanField()),
            ],
        ),
    ]
